dependencies:
  - name: helper-installplan-approver
    version: 0.1.0
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
apiVersion: v2
appVersion: v1.4.2
description: An addon for cert-manager to sign certificates using AWS PCA
name: aws-privateca-issuer
type: application
version: 1.6.0
