dependencies:
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
  - name: helper-operator
    version: 1.1.0
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
name: cluster-efs
version: 0.4.14
apiVersion: v2
description: Chart to deploy the efs operator and supporting componenets
