apiVersion: v2
name: loki-operator
description: Deploys the Loki Operator for OpenShift log aggregation and storage using Grafana Loki
type: application
version: 0.1.17
dependencies:
  - name: helper-operator
    version: 1.1.0
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
    condition: helper-status-checker.enabled