name: cluster-logging
version: 0.5.14
apiVersion: v2
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
  - name: helper-status-checker
    version: 4.4.3
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
    condition: helper-status-checker.enabled
  - name: loki-operator
    version: ~0.1.5
    repository: https://rh-mobb.github.io/validated-pattern-helm-charts/
    condition: loki-operator.enabled
